landing_getting_started: |-
  // In main.js
  import { createApp } from 'vue';
  import App from './App.vue';
  import InstantSearch from 'vue-instantsearch/vue3/es';
  import "instantsearch.css/themes/algolia-min.css";
  import "@meilisearch/instant-meilisearch/templates/basic_search.css";

  createApp(App).use(InstantSearch).mount('#app');


  // In App.vue
  <template>
    <ais-instant-search
      :search-client="searchClient"
      index-name="steam-video-games"
    >
      <ais-search-box />
      <ais-hits>
        <template v-slot:item="{ item }">
          <ais-highlight :hit="item" attribute="name" />
        </template>
      </ais-hits>
    </ais-instant-search>
  </template>

  <script>
  import { instantMeiliSearch } from "@meilisearch/instant-meilisearch";

  export default {
    data() {
      return {
        searchClient: instantMeiliSearch(
          "https://integration-demos.meilisearch.com",
          "99d1e034ed32eb569f9edc27962cccf90b736e4c5a70f7f5e76b9fab54d6a185"
        ),
      };
    },
  };
  </script>

getting_started_front_end_integration_md: |-
  The following example uses [Vue 3](https://vuejs.org/), a JavaScript framework for building web user interfaces.

  ```html
  <!DOCTYPE html>
  <html lang="en">

  <head>
    <meta charset="utf-8" />

    <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@meilisearch/instant-meilisearch/templates/basic_search.css" />
  </head>

  <body>
    <div id="app" class="wrapper">
      <ais-instant-search :search-client="searchClient" index-name="steam-video-games">
        <ais-search-box></ais-search-box>
        <ais-hits>
          <template v-slot:item="{ item }">
            <ais-highlight :hit="item" attribute="name" />
         </template>
          </ais-hits>
      </ais-instant-search>
    </div>
  </body>

  <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue-instantsearch@4.5.0/vue3/umd/index.js"></script>
  <script
    src="https://cdn.jsdelivr.net/npm/@meilisearch/instant-meilisearch/dist/instant-meilisearch.umd.min.js">
  </script>

  <script type="module">
    const InstantSearch = {
      install(localVue) {
        Object.keys(VueInstantSearch).forEach(widgetName => {
          localVue.component(VueInstantSearch[widgetName].name, VueInstantSearch[widgetName]);
        });
      },
    };


    const app = Vue
      .createApp({
        data() {
          return {
            searchClient: instantMeiliSearch(
              'https://integration-demos.meilisearch.com/',
              '99d1e034ed32eb569f9edc27962cccf90b736e4c5a70f7f5e76b9fab54d6a185',
            )
          }
        }
      })
      .use(InstantSearch)
      .mount('#app')
  </script>

  </html>
  ```

  Here's what's happening:
  - To use `instant-meilisearch` with Vue, you must add `<ais-instant-search>`, `<ais-search-box>`, and `<ais-hits>` to your application's HTML. These components are mandatory when generating the `instant-meilisearch` interface
  - Other Vue components such as `<ais-configure>` and `<ais-highlight>` are optional. They offer greater control over `instant-meilisearch`'s behavior and appearance
  - The three `<script src="..">` tags import libraries needed to run `instant-meilisearch` with Vue
  - The fourth and final `<script>` creates a new Vue instance and instructs it to use `instant-meilisearch`
