landing_getting_started_1: |-
  // In main.js
  import Vue from 'vue';
  import App from './App.vue';
  import InstantSearch from 'vue-instantsearch';

  Vue.use(InstantSearch);

  new Vue({
    el: '#app',
    render: h => h(App),
  });


  // In App.vue
  <template>
    <ais-instant-search :search-client="searchClient" index-name="movies">
      <ais-search-box />
      <ais-hits>
        <div slot="item" slot-scope="{ item }">
          <h2>{{ item.title }}</h2>
        </div>
      </ais-hits>
    </ais-instant-search>
  </template>

  <script>
  import { instantMeiliSearch } from '@meilisearch/instant-meilisearch';

  export default {
    data() {
      return {
        searchClient: instantMeiliSearch(
          "http://localhost:7700",
          "searchKey"
        ),
      };
    },
  };
  </script>
getting_started_front_end_integration_md: |-
  The following example uses [Vue 2](https://vuejs.org/), the second major release of Vue, a JavaScript framework for building web user interfaces.

  ```html
  <!DOCTYPE html>
  <html lang="en">

  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@meilisearch/instant-meilisearch/templates/basic_search.css" />
  </head>

  <body>
    <div id="app" class="wrapper">
      <ais-instant-search :search-client="searchClient" index-name="movies">
        <ais-configure :hits-per-page.camel="10" />
        <ais-search-box placeholder="Search here…" class="searchbox"></ais-search-box>
        <ais-hits>
          <div slot="item" slot-scope="{ item }">
            <ais-highlight :hit="item" attribute="title" />
          </div>
        </ais-hits>
      </ais-instant-search>
    </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue-instantsearch/vue2/umd/index.js"></script>
  <script
    src="https://cdn.jsdelivr.net/npm/@meilisearch/instant-meilisearch/dist/instant-meilisearch.umd.min.js"></script>
  <script>
    Vue.use(VueInstantSearch)
    var app = new Vue({
      el: '#app',
      data: {
        searchClient: instantMeiliSearch('http://127.0.0.1:7700')
      }
    })
  </script>

  </html>
  ```

  Here's what's happening:

  - To use `instant-meilisearch` with Vue, you must add `<ais-instant-search>`, `<ais-search-box>`, and `<ais-hits>` to your application's HTML. These components are mandatory when generating the`instant-meilisearch` interface
  - Other Vue components such as `<ais-configure>` and `<ais-highlight>` are optional. They offer greater control over `instant-meilisearch`'s behavior and appearance
  - The first two`<script src="..">` tags import libraries needed to run `instant-meilisearch` with Vue
  - The third and final `<script>` creates a new Vue instance and instructs it to use `instant-meilisearch`
